//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CommentCourse = new HashSet<CommentCourse>();
        }
    
        public int CourseID { get; set; }
        public string CourseSort { get; set; }
        public System.DateTime CourseTime { get; set; }
        public string CourseTitle { get; set; }
        public string CourseIntroduce { get; set; }
        public string CourseVideo { get; set; }
        public string CoursePhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentCourse> CommentCourse { get; set; }
    }
}
