//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YanShenWangEntities : DbContext
    {
        public YanShenWangEntities()
            : base("name=YanShenWangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carousel> Carousel { get; set; }
        public virtual DbSet<CommentCourse> CommentCourse { get; set; }
        public virtual DbSet<CommentGoods> CommentGoods { get; set; }
        public virtual DbSet<CommentPost> CommentPost { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetials> OrderDetials { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<ReplyCommentCourse> ReplyCommentCourse { get; set; }
        public virtual DbSet<ReplyCommentGoods> ReplyCommentGoods { get; set; }
        public virtual DbSet<ReplyCommentPost> ReplyCommentPost { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<Strategy> Strategy { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Course_hf> Course_hf { get; set; }
        public virtual DbSet<Course_pl> Course_pl { get; set; }
        public virtual DbSet<Goods_hf> Goods_hf { get; set; }
        public virtual DbSet<Goods_pl> Goods_pl { get; set; }
        public virtual DbSet<Post_hf> Post_hf { get; set; }
        public virtual DbSet<Post_pl> Post_pl { get; set; }
        public virtual DbSet<PostShow> PostShow { get; set; }
        public virtual DbSet<shopping_cart> shopping_cart { get; set; }
    }
}
