//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string SchoolPhoto { get; set; }
        public string SIntroduce { get; set; }
        public string KYmessage { get; set; }
        public string ZYmessage { get; set; }
        public string ZMTeacher { get; set; }
        public string PaiMing { get; set; }
        public string QuNianZhaoShengRenShu { get; set; }
        public string YouShiZhuanYe { get; set; }
        public string Sort { get; set; }
    }
}
