//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCartID { get; set; }
        public int UserID { get; set; }
        public int GoodsID { get; set; }
        public int Number { get; set; }
        public int Price { get; set; }
        public Nullable<int> flag { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
